#!/usr/bin/env ruby

data, code = eval(File.read "profil"), File.read(ARGV.first)
commit = follower = score = 0
class Fixnum; def method_missing(m); $repo[m.to_s]; end; end
data["repositories"].each do |repo|
  repository, $repo = 0, repo
  eval code
  score += repository
end
puts score + data["commits"] * commit + data["followers"] * follower
